apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-deployment
  template:
    metadata:
      name: hello-deployment
      labels:
        app: hello-deployment
    spec:
      containers:
        - name: hello-deployment
          image: luizfelipems5/hello-spring:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      restartPolicy: Always
      